name: Picoworkers CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: who am ii?
      run: whoami

    - run: curl -sL https://rpm.nodesource.com/setup_14.x | bash -
    - run: yum install -y nodejs
    - run: node --version
    - run: rm -rf node_modules
    - name: install denpendences
      run: npm install

    - name: eslint
      run: npm run lint
  build:
    name: Build
    runs-on: self-hosted
    needs: ["test"]
    if: github.ref == 'refs/heads/main'
    steps:
    - run: node --version
    - run: ls -al
    - run: |
        npm run build --if-present
  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: ["build"]
    if: github.ref == 'refs/heads/main'
    steps:
    - name: migration database
      run: npm run migration:run
    - run: |
       pm2 start ecosystem.config.js
       echo deploy successful
